### ISSUE TITLE
English instructions?

### ISSUE THREAD

**Issue by ftjuh** [luisllamasbinaburo/Arduino-AsyncSonar#5]
Hi Luis,

this looks like a well done and powerful library and I am considering using it in my [I2Cwrapper project](https://github.com/ftjuh/I2Cwrapper).

However, the lack of English instructions makes me hesitant. While DeepL and google translations help a lot, I'd feel more comfortable with a human made, or at least human supervised, translation, so that I am sure there are no misconceptions.

So any chance for that?

Jan

Edit: I just saw the [PR](https://github.com/luisllamasbinaburo/Arduino-AsyncSonar/pull/4) by @max-hans from June, so the work [has already been done](https://github.com/luisllamasbinaburo/Arduino-AsyncSonar/blob/14358cfac23d0128747edee9e0b94f11e51f1f57/README.md).

**Comment by luisllamasbinaburo** [comment]
Added a new file readme.en.md. Thanks to @max-hans for the translation
